name: Learning Actions

on: push

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
           - name: Show Date
             run: date
           - name: Show Files
             run: ls
           - name: Greetings
             run: echo "Hello there guys, welcome back to ytf"