name: Iris_classifier_model

on: push

jobs:
    classify_iris:
        runs-on: ubuntu-latest
        steps:
            - name: Copy to empty repo
              uses: actions/checkout@v4
            - name: Install python
              uses: actions/setup-python@v5
            - name: Install Dependancies
              run: |
                pip install -r requirements.txt
            - name: Train Sklearn Model
              run: python train.py